### ISSUE TITLE
I can not get train.yx.txt and test.yx.txt

### ISSUE THREAD

**Issue by liuxiaoxinhappy** [Atomu2014/pnn-demo#2]
Hello,
I donot have train.yx.txt and test.yx.txt in my 2997 folder,Why?
Thanks!

**Comment by benarba** [comment]
I think they changed the name. Just remove the ".yx" (train.txt, test.txt). It works for me.

**Comment by kidtronnix** [comment]
Yeah confirmed @benarba. Once i saw it was just labelled differently was able to run.

**Comment by Atomu2014** [comment]
Yes, this is just file-name stuff.
Sorry for the late response, any problems you can contact me via email, thx.
email: kevinqu@apex.sjtu.edu.cn.
