### ISSUE TITLE
About max_pool_3d

### ISSUE THREAD

**Issue by allanruin** [Atomu2014/pnn-demo#3]
I don't quite understand the implementation part of max_pool_3d （max_pool_xd all alike）. I try some data and obeserve that max_pool_3d is the same as just use tf.nn.top_k. 

For example:
```
aa = [[[175 192  20  74  21  26 105 181]
  [  3 168 141  56  11  62  69  20]
  [194  40 133  78  74  12 127  75]
  [ 19   5  96   2 193 168  11 107]
  [  7  10  97 182  24 121 133 118]
  [168 190 139 147 142  53  63  87]]

 [[  4  78 143 121  38  82 126  43]
  [ 84 161 132  40 130  71  84 121]
  [139 188   1 148 197  10 157  53]
  [ 74  56  78 193 145  45 184 186]
  [ 26 140 145  67  15 196   7  18]
  [ 25 177  41  64 138  72  88 185]]

 [[188  46 154  34 175 104 170  20]
  [ 12 114  81  82 185 100 199 123]
  [128  64 132 191 149 121  22 141]
  [ 72 148 186   4 110 185 173 125]
  [138  23 152  27 115  14 193  30]
  [ 61  18  51 139  71  23  60 163]]]

a = tf.constant(aa)
with tf.Session() as sess:
        print(sess.run(a))
        print(sess.run(max_pool_3d(a, 2)))

```
I get 

```
[[[192 181]
  [168 141]
  [194 133]
  [193 168]
  [182 133]
  [190 168]]

 [[143 126]
  [161 132]
  [197 188]
  [193 186]
  [196 145]
  [185 177]]

 [[188 175]
  [199 185]
  [191 149]
  [186 185]
  [193 152]
  [163 139]]]
```

and if I change max_pool_3d to this:
```
def max_pool_3d(params, k):
    tt, indices = tf.nn.top_k(params, k, sorted=False)
    return tt
```
then I get 

```
[[[181 192]
  [141 168]
  [133 194]
  [168 193]
  [133 182]
  [168 190]]

 [[126 143]
  [132 161]
  [188 197]
  [186 193]
  [145 196]
  [177 185]]

 [[175 188]
  [185 199]
  [149 191]
  [185 186]
  [152 193]
  [139 163]]]
```

The only difference is that use `tf.nn.top_k`  the values are in ascending order, while use author's max_pool_3d code, the values are in descending order.

As _A Convolutional Click Prediction Model_  stated, 

> "The flexible p-max pooling layer can not only select the p most key features, but also preserve the relative order of those features, which plays a critical role in the sequential click prediction."

However, both `tf.nn.top_k` and `max_pool_3d` do not have such property.

I greatly appreciate author's effort of sharing the implementation, and I learn a lot from the code.

above are a little confusion of mine.  Could anyone explain a bit for me ? Thank you.

**Comment by Atomu2014** [comment]
I remember that top_k was unable to perform on 3d tensors. It seems that this op is improved in tensorflow's latest version. As for flexible pooling, this number p is determined by hand according to the formula.
Sorry for the late response, any problems you can contact me via email, thx.
email: kevinqu@apex.sjtu.edu.cn.
