### ISSUE TITLE
A question about FM product unit.

### ISSUE THREAD

**Issue by qldeng** [Atomu2014/pnn-demo#6]
HI, In the class of DeepFM, i have a question about the code of computing product unit:
p = 0.5 * tf.reduce_sum(
tf.square(tf.reduce_sum(xv, 2)) -
tf.reduce_sum(tf.square(xv), 2)
)
according to the FM formula, does it should be like this?
p = 0.5 * tf.reduce_sum(
tf.square(tf.reduce_sum(xv, 1)) -
tf.reduce_sum(tf.square(xv), 1),
1)

**Comment by Atomu2014** [comment]
yes you are right!
fix this bug latter
