### ISSUE TITLE
Question about sampling method

### ISSUE THREAD

**Issue by sl7rf** [Atomu2014/pnn-demo#8]
Thanks for sharing the code. It helps a lot! 

Actually my question comes from the `product-net paper`. Four data sets (**Criteo, Avazu, iPinyou, Huawei**) were used in performance evaluation, and only **Criteo** data was down-sampled on negative samples to reach a pos ratio of 0.5 (_''Because of the enormous data volume and serious label unbalance (only 3% samples are positive), we apply negative downsampling to keep the positive ratio close to 50%. "_). But **iPinyou** and **Huawei** also have very low CTR (lower than 3%).  Are there any reasons that you didnt performed sampling on these two data sets? Thanks

**Comment by Atomu2014** [comment]
The main reason is data volume.
Criteo has about 100 million examples after sampling.
iPinYou has 20 million examples without sampling.
Huawei has 57 million examples without sampling.
